name: Go Cross Build
description: Cross-compiles Go binaries for one or more platforms

inputs:
  go-version:
    description: Go version used for compilation
    default: "1.26.x"

  platforms:
    description: Comma-separated os/arch pairs
    default: linux/amd64,linux/arm64

  ouput-pattern:
    description: Path pattern to parse files against. Placeholders become named fields
    default: dist/{os}/{arch}/{name}

  cgo-enabled:
    description: Compile using cgo
    default: "false"

  ldflags:
    description: Go build ldflags
    default: "-w -s"

  context:
    description: Build context
    default: .

  working-directory:
    description: Working Directory
    default: .

  run-tests:
    description: Whether to run tests or not
    default: "true"

  build-args:
    description: Build args passed into packages, e.g. 'main.Version=v1.0.0' or 'Version.v1.0.0' (defaults to `buildargs-package`)
    default: ""

  build-args-package:
    description: Package path used for build-args keys with no dot (no explicit package)
    default: buildinfo

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod tidy

    - if: inputs.run-tests == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go test ./... -v

    - if: inputs.build-args != ''
      id: ldflags
      shell: bash
      run: |
        ldflags=""

        while IFS= read -r line; do
          line="$(echo "$line" | xargs)"  # trim whitespace
          [ -z "$line" ] && continue

          key="${line%%=*}"
          value="${line#*=}"

          if [[ "$key" != *.* ]]; then
            key="${{ inputs.buildargs-package }}.$key"
          fi

          ldflags="$ldflags -X '${key}=${value}'"
        done <<< "${{ inputs.build-args }}"

        echo "value=$ldflags" >> "$GITHUB_OUTPUT"

    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        IFS=',' read -ra platforms <<< "${{ inputs.platforms }}"

        cgo=0
        [ "${{ inputs.cgo-enabled }}" = "true" ] && cgo=1

        for platform in "${platforms[@]}"; do
          IFS='/' read -ra p <<< "$platform"

          os="${p[0]}"; arch="${p[1]}"
          path="${{ inputs.output-dir }}/$os/$arch/${{ inputs.binary-name }}"

          if [[ "$os" == "windows" ]]; then
            path+=".exe"
          fi

          mkdir -p "$(dirname "$path")"
          echo "Building $path"

          GOOS="$os" GOARCH="$arch" CGO_ENABLED=$cgo \
            go build -ldflags="${{ inputs.ldflags }} ${{ steps.ldflags.outputs.value }}" -o "$path" ${{ inputs.context }}
        done
